### ISSUE TITLE
cosmic-de/pop-fonts-9999 masked

### ISSUE THREAD

**Issue by erikbadman** [fsvm88/cosmic-overlay#18]
Not sure if this should be an issue but I will ask here. I just tried to install this and got:

 ```
emerge -1 cosmic-meta pop-theme-meta -pv

These are the packages that would be merged, in order:

Calculating dependencies... done!
Dependency resolution took 1.50 s (backtrack: 1/20).


!!! All ebuilds that could satisfy "=cosmic-de/pop-fonts-9999" have been masked.
!!! One of the following masked packages is required to complete your request:
- cosmic-de/pop-fonts-9999::cosmic-overlay (masked by: missing keyword)

(dependency required by "cosmic-de/pop-theme-meta-9999::cosmic-overlay" [ebuild])
(dependency required by "pop-theme-meta" [argument])
For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.
```

I see here that it was just unkeyworded, are we supposed to keyword this manually or was this a mistake?

https://github.com/fsvm88/cosmic-overlay/pull/16/files#diff-1c9a09bd1852d72ab0b7b475080f5aab8f879169d79232f561309b0e1068bceaR17

**Comment by erikbadman** [comment]
Same for: 

cosmic-de/system76-power
cosmic-de/cosmic-wallpapers

**Comment by fsvm88** [comment]
I have readded KEYWORDS for these 3 ebuilds, missed the alpha1/alpha2 dependency in the earlier PR. Should be resolved (I can run `emerge -1 =cosmic-de/cosmic-meta-1.0.0_alpha2 -pv` successfully).

**Comment by joostruis** [comment]
Seems that cosmic-de/system76-power-9999 still lacks the ~amd64 keyword.

**Comment by fsvm88** [comment]
Done, sorry, the logic was a bit different and I missed it :)

**Comment by sebasmagri** [comment]
I'm still seeing wallpapers masked by Unknown license(s) here:
```
!!! All ebuilds that could satisfy "=cosmic-de/cosmic-wallpapers-9999" have been masked.
!!! One of the following masked packages is required to complete your request:
- cosmic-de/cosmic-wallpapers-9999::cosmic-overlay (masked by: Unknown license(s))
```

**Comment by fsvm88** [comment]
At the time I wrote the build, I did a pass just to find out all relevant licenses for each package. For cosmic-wallpapers the issue is that many files don't have attribution. At the time, I went with "Unknown".

I improved the situation a bit by following the advice here: https://devmanual.gentoo.org/general-concepts/licenses/

Can you test if this works? (I run with `ACCEPT_LICENSE="*"` in make.conf, so I never noticed).

**Comment by sebasmagri** [comment]
Yes, that works!

**Comment by joostruis** [comment]
I have the issue with cosmic-de/pop-appstream-data-9999 still.

**Comment by fsvm88** [comment]
Done, and I identified pop-gtk-theme being in the same situation as well. Should have all been fixed now.
